# [START gae_python37_custom_runtime]
runtime: python37
entrypoint: uwsgi --http-socket :8080 --wsgi-file create_app_engine_queue_task.py --callable app --master --processes 1 --threads 2

env_variables:
  DB_USER: root
  DB_PASS: 12345
  DB_NAME: pass--db_name
  CLOUD_SQL_CONNECTION_NAME: pass cloud sql url
# [END gae_python37_custom_runtime]
